name=xiaomi-XMRM-006
version=1.0.0
author=Mateusz Niedobecki
maintainer=Mateusz Niedobecki
sentence=Library for Xiaomi XMRM-006 BLE remote receiver on ESP32-C3.
paragraph=Connects to Xiaomi XMRM-006 BLE remote, decodes buttons, provides raw and decoded events, ready state and reconnect handling.
category=Communication
url=https://github.com/Mataas08
architectures=esp32
